/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/credit` | `/credit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/distributors` | `/distributors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ott` | `/ott`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/packages` | `/packages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/resellers` | `/resellers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/subscribers` | `/subscribers`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/credit` | `/credit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/distributors` | `/distributors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ott` | `/ott`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/packages` | `/packages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/resellers` | `/resellers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/subscribers` | `/subscribers`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/channels${`?${string}` | `#${string}` | ''}` | `/channels${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/credit${`?${string}` | `#${string}` | ''}` | `/credit${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/distributors${`?${string}` | `#${string}` | ''}` | `/distributors${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ott${`?${string}` | `#${string}` | ''}` | `/ott${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/packages${`?${string}` | `#${string}` | ''}` | `/packages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/resellers${`?${string}` | `#${string}` | ''}` | `/resellers${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/subscribers${`?${string}` | `#${string}` | ''}` | `/subscribers${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/credit` | `/credit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/distributors` | `/distributors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ott` | `/ott`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/packages` | `/packages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/resellers` | `/resellers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/subscribers` | `/subscribers`; params?: Router.UnknownInputParams; };
    }
  }
}
